// Generated by scripts/gen_registry_types.ts - DO NOT EDIT MANUALLY
// Source: docs/registry/fields_v1.json
// Generated at: 2025-09-22T13:20:44.102Z

export type FieldId = 'preferred_pace' | 'connection_purpose' | 'birth_date' | 'birth_time' | 'birth_location' | 'legacy_field';

export const REGISTRY: Record<FieldId, {
  owner: string;
  exposure: string;
  status: 'active' | 'parked';
  writable: boolean;
  read_path: string;
  writer: string;
  version: string;
  enum?: string[];
}> = {
  'preferred_pace': {
    owner: 'preferences',
    exposure: 'user',
    status: 'active',
    writable: true,
    read_path: 'user.preferences.preferred_pace',
    writer: 'preferences',
    version: '1.0.0', enum: ["slow","medium","fast"]
  },
  'connection_purpose': {
    owner: 'profile',
    exposure: 'user',
    status: 'active',
    writable: false,
    read_path: 'user.profile.connection_purpose',
    writer: 'unavailable',
    version: '1.0.0'
  },
  'birth_date': {
    owner: 'profile',
    exposure: 'user',
    status: 'active',
    writable: true,
    read_path: 'user.birth_data.date',
    writer: 'birth_data',
    version: '1.0.0'
  },
  'birth_time': {
    owner: 'profile',
    exposure: 'user',
    status: 'active',
    writable: true,
    read_path: 'user.birth_data.time',
    writer: 'birth_data',
    version: '1.0.0'
  },
  'birth_location': {
    owner: 'profile',
    exposure: 'user',
    status: 'active',
    writable: true,
    read_path: 'user.birth_data.location',
    writer: 'birth_data',
    version: '1.0.0'
  },
  'legacy_field': {
    owner: 'system',
    exposure: 'internal',
    status: 'parked',
    writable: false,
    read_path: 'user.legacy.field',
    writer: 'unavailable',
    version: '0.9.0'
  }
} as const;

export function isFieldId(x: string): x is FieldId {
  return x in REGISTRY;
}

// Field counts for artifacts
export const FIELD_COUNTS = {
  total: 6,
  active: 5,
  parked: 1
} as const;
