#!/usr/bin/env ts-node

import * as fs from 'fs';
import * as path from 'path';

// Registry field interface based on the spec
interface RegistryField {
  id: string;
  owner: string;
  exposure: string;
  status: 'active' | 'parked';
  writable: boolean;
  read_path: string;
  writer: string;
  version: string;
  enum?: string[];
}

interface RegistryData {
  version: string;
  fields: RegistryField[];
}

function validateField(field: any, index: number): RegistryField {
  const required = ['id', 'owner', 'exposure', 'status', 'writable', 'read_path', 'writer', 'version'];
  
  for (const prop of required) {
    if (!(prop in field)) {
      throw new Error(`Field at index ${index} missing required property: ${prop}`);
    }
  }
  
  if (typeof field.id !== 'string' || field.id.length === 0) {
    throw new Error(`Field at index ${index} has invalid id`);
  }
  
  if (!['active', 'parked'].includes(field.status)) {
    throw new Error(`Field at index ${index} has invalid status: ${field.status}`);
  }
  
  if (typeof field.writable !== 'boolean') {
    throw new Error(`Field at index ${index} has invalid writable property`);
  }
  
  return field as RegistryField;
}

function generateRegistryTypes(registryData: RegistryData): string {
  const fields = registryData.fields;
  const fieldIds = fields.map(f => f.id);
  
  // Generate FieldId union type
  const fieldIdType = fieldIds.map(id => `'${id}'`).join(' | ');
  
  // Generate REGISTRY object
  const registryEntries = fields.map(field => {
    const enumProp = field.enum ? `, enum: ${JSON.stringify(field.enum)}` : '';
    return `  '${field.id}': {
    owner: '${field.owner}',
    exposure: '${field.exposure}',
    status: '${field.status}',
    writable: ${field.writable},
    read_path: '${field.read_path}',
    writer: '${field.writer}',
    version: '${field.version}'${enumProp}
  }`;
  }).join(',\n');
  
  return `// Generated by scripts/gen_registry_types.ts - DO NOT EDIT MANUALLY
// Source: docs/registry/fields_v1.json
// Generated at: ${new Date().toISOString()}

export type FieldId = ${fieldIdType};

export const REGISTRY: Record<FieldId, {
  owner: string;
  exposure: string;
  status: 'active' | 'parked';
  writable: boolean;
  read_path: string;
  writer: string;
  version: string;
  enum?: string[];
}> = {
${registryEntries}
} as const;

export function isFieldId(x: string): x is FieldId {
  return x in REGISTRY;
}

// Field counts for artifacts
export const FIELD_COUNTS = {
  total: ${fields.length},
  active: ${fields.filter(f => f.status === 'active').length},
  parked: ${fields.filter(f => f.status === 'parked').length}
} as const;
`;
}

function main() {
  try {
    const registryPath = path.join(process.cwd(), 'docs/registry/fields_v1.json');
    const outputPath = path.join(process.cwd(), 'src/types/registry.ts');
    const artifactPath = path.join(process.cwd(), 'artifacts/fe_registry_types.txt');
    
    // Read and validate registry JSON
    if (!fs.existsSync(registryPath)) {
      throw new Error(`Registry file not found: ${registryPath}`);
    }
    
    const registryContent = fs.readFileSync(registryPath, 'utf-8');
    const registryData: RegistryData = JSON.parse(registryContent);
    
    if (!registryData.fields || !Array.isArray(registryData.fields)) {
      throw new Error('Registry must have a fields array');
    }
    
    // Validate each field
    const validatedFields = registryData.fields.map((field, index) => 
      validateField(field, index)
    );
    
    registryData.fields = validatedFields;
    
    // Generate TypeScript types
    const generatedCode = generateRegistryTypes(registryData);
    
    // Ensure output directory exists
    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }
    
    // Write generated types
    fs.writeFileSync(outputPath, generatedCode, 'utf-8');
    
    // Generate artifact file
    const activeFields = validatedFields.filter(f => f.status === 'active');
    const parkedFields = validatedFields.filter(f => f.status === 'parked');
    
    const artifactContent = `fields=${validatedFields.length} active=${activeFields.length} parked=${parkedFields.length}`;
    
    // Ensure artifacts directory exists
    const artifactDir = path.dirname(artifactPath);
    if (!fs.existsSync(artifactDir)) {
      fs.mkdirSync(artifactDir, { recursive: true });
    }
    
    fs.writeFileSync(artifactPath, artifactContent, 'utf-8');
    
    console.log(`✅ Generated registry types: ${outputPath}`);
    console.log(`✅ Generated artifact: ${artifactPath}`);
    console.log(`📊 Fields: ${validatedFields.length} total, ${activeFields.length} active, ${parkedFields.length} parked`);
    
  } catch (error) {
    console.error('❌ Registry types generation failed:', error.message);
    process.exit(1);
  }
}

// Run main function directly in ESM
main();
